### ISSUE TITLE
Error handling after load error

### ISSUE THREAD

**Issue by matthew-white** [enketo/enketo#1284]

**Comment by lognaturel** [comment]
Sorry @matthew-white, you must be getting confusing notifications!

There's one last lone issue left in https://github.com/enketo/enketo-express: https://github.com/enketo/enketo-express/issues/202

I was getting failures trying to move it that made me think I was being rate limited. But actually it looks like it just got into some kind of bad state. I guess it will stay there!

**Comment by lognaturel** [comment]
First attempt was at https://github.com/enketo/enketo/issues/1265. So I tried 19 times, I guess. 🙈 Only just started noticing these ghost issues. Software is hard!
