### ISSUE TITLE
drawing changes when loaded from a record

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo#1288]
**Describe the bug**

When loading a record that contains a drawing, the act of loading it changes the drawing file (name), even when the user makes no changes to it.

**To Reproduce**
Steps to reproduce the behavior. 

1. Load a record containing a drawing (widget) with a drawing file. Here is a [test form](https://docs.google.com/spreadsheets/d/1WlWhO8D2DAffkGT9EpnVY-lMu6Tmm_M1WDLwtP7kC-A/edit?usp=sharing)
2. Submit
3. Note how the drawing file was updated in the submission (e.g. by looking at the file name).

**Expected behavior**
For the drawing widget to leave a loaded drawing unchanged if the user makes no changes to it.

**Additional context**
~~I think the drawing widget revamp in March 2023, omitted the mechanism that set `this.value` in the drawing widget upon loading an existing drawing. This served to make sure no change event was propagated in `_updateValue` for loading an existing drawing. I don't immediately see the relevant code change causing this though.~~

**Comment by lognaturel** [comment]
Previously filed at https://github.com/enketo/enketo/issues/932 Good to know it's just image-related and that there might be a quick fix!

**Comment by lognaturel** [comment]
@MartijnR do you plan on taking a look at this one? With the hint you've given I could look around. Either way, I can do a release soon after there's a fix.

**Comment by MartijnR** [comment]
Thanks @lognaturel ! I missed that earlier filed issue. 

I hope to have a couple of hours tomorrow afternoon to look into this issue. Happy to do so (or to review).

Btw, OpenClinica also noticed some scaling issues that you mentioned in #932 (with most of the signature actually being cut off) but we're still working on trying to reproduce this locally and to confirm that Enketo is really the culprit. Probably a different issue.
