### ISSUE TITLE
new drawing on low-resolution screen is cut off in submission (pages mode, non-last page)

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo#1291]
**Describe the bug**
When creating a drawing on small resolution mobile or desktop screen only the top left corner is submitted when the form is in Pages mode and the drawing is not on the last page.

**To Reproduce**
Steps to reproduce the behavior. If applicable please include the smallest possible XLSForm or XForm (as zip or link).

1. Load [this form](https://docs.google.com/spreadsheets/d/1WlWhO8D2DAffkGT9EpnVY-lMu6Tmm_M1WDLwtP7kC-A/edit?usp=sharing) in enketo-express
2. Easiest is to set devtools to mobile mode (I used iPhone SE simulation) or to make the regular desktop screen quite small.
3. Create a drawing
4. Submit
5. Inspect the submitted image and notice that it has been cut off

**Expected behavior**
For the complete image to be submitted.

**Screenshots**

<img width="444" alt="Screenshot 2024-01-02 at 1 49 18 PM" src="https://github.com/enketo/enketo/assets/627350/477eb40d-b642-4e7a-92b6-76808df152a9">

Submitted:

![drawing-13_49_10](https://github.com/enketo/enketo/assets/627350/46b8ef9c-f4b3-4d63-84ea-e9716748cdab)

**Browser and OS (please complete the following information):**

- Tested in Chrome on Mac OS 13.6.1 and Chrome and Safari on the latest iOS 

**Additional context**

Though it doesn't deal with loading an existing image, it sounds like the cause might be related to what is mentioned in https://github.com/enketo/enketo/pull/1290#issuecomment-1856512944 and https://github.com/enketo/enketo/pull/1290#issuecomment-1864785839

**Comment by lognaturel** [comment]
Agreed it's very likely related. Maybe the best short-term approach is to roll back the change that kept higher resolution images. We know that change was important to some users and rolling it back will be disruptive but now that we know there's data loss here it probably doesn't make sense to keep as it is.

**Comment by MartijnR** [comment]
Yes, that makes sense, I think.
