### ISSUE TITLE
Draw image filename postfix changes on `canvasreload` event if image value did not change

### ISSUE THREAD

**Issue by jkuester** [enketo/enketo#1323]
**Describe the bug**
First off, I just want to confirm that this issue presents in the new (aka "old") version of the Draw widget for enketo-core `8.1.0+`.

Basically, the `_updateValue` function in the Draw widget will [always assign a new value](https://github.com/enketo/enketo/blob/05e5281949e54c0be6592996513ab592a7b55403/packages/enketo-core/src/widget/draw/draw-widget.js#L448) for the `filenamePostfix` every time the function is called with a different value in the pad.  However, the `originalInputValue` field is only reset if `changed === true` which is NOT the case if `_updateValue`  was called by [a `canvasreload` event](https://github.com/enketo/enketo/blob/05e5281949e54c0be6592996513ab592a7b55403/packages/enketo-core/src/widget/draw/draw-widget.js#L236).

Changing the `originalInputValue` is what causes the text filename _with the postfix_ to be saved in the form model as the "answer" for that question. However, when the postfix for the file changes and  `originalInputValue` is not updated (as in the case of the `canvasreload` event, then a mismatch occurs between the filename (e.g. as [returned by `fileManager.getCurrentFiles`](https://github.com/enketo/enketo/blob/05e5281949e54c0be6592996513ab592a7b55403/packages/enketo-core/src/js/file-manager.js#L133)) and the value recorded for that question in the model string (e.g. as returned by [`form.getDataStr()`](https://github.com/enketo/enketo/blob/05e5281949e54c0be6592996513ab592a7b55403/packages/enketo-core/src/js/form.js#L556)).  

**To Reproduce**
This behavior is not really noticeable by the user when filling out the form. The form can be filled out successfully. The problem occurs after submitting the form if anyone tries to correlate the string value saved for the Draw question (the filename+postfix) with the name of the actual image file recorded by the form. These will not match if the `canvasreload` event is triggered after the last drawing input is made on the canvas.  

Basically, to trigger the problem behavior:

1. Open a form with a draw widget
2. Draw on the canvas
3. Resize your webpage so that the size of the canvas changes
4. Complete the form and see that the name of the image file does not match name stored in the form model

Even though this behavior is not visible to the user, it is possible to see the problem behavior in action out on https://staging.enketo.getodk.org/.  

- I uploaded a form with a draw widget to https://getodk.org/xlsform/
- Then, after opening the form, I use my browser DevTools to place a breakpoint [in the `nodeset.setVal` function](https://github.com/enketo/enketo/blob/05e5281949e54c0be6592996513ab592a7b55403/packages/enketo-core/src/js/nodeset.js#L114)
- When I draw on the canvas, the `nodeset.setVal` function is triggered. I can see that `newVals` is always the filename + a new postfix value each time I draw on the the canvas.  
- However, when I change the size of my browser window so that the size of the canvas is updated, the `nodeset.setVal` function is not triggered.  BUT, looking at the actual HTML page body, I can see the `data-filename-postfix` value for the `input` of my draw question get updated as the canvas refreshes.

**Expected behavior**
I expect that the name of the image file attachment should match the string value recorded for the draw question in the model.  

Looking at the code for the `draw._updateValue` function, it seems like we could avoid resetting the `filenamePostfix` except when `changed === true` (and `originalInputValue` is getting reset).  I am not sure why we would need/want a different postfix for `canvasreload` events.  (But maybe I am missing something here???)  I have tried moving the postfix code inside the `if (changed)` block and it resolved the issue (and did not create any new issues that I could detect).  If this seems like a reasonable fix, I am happy to submit a PR!

**Browser and OS (please complete the following information):**

- OS: Debian
- Browser: Chromium 124.0.6367.60 
- Enketo: Reproducible on https://staging.enketo.getodk.org/

**Comment by lognaturel** [comment]
Thanks for the detailed report, @jkuester! Currently the image does change when the canvas changes. We tried to maintain the image size on canvas resize but weren't quite able to get it right and ended up backing out of the change.

Can you confirm that the image does actually change? In that case I think it makes sense for the postfix to change but it also should be updated in the model? I feel like we ran into issues related to this but I can't quite remember. You might want to take a look at https://github.com/enketo/enketo/pull/1292 and related issues. In particular, you'll want to make sure that any change you propose is verified with `pages` mode on the first, middle and last screens.

**Comment by jkuester** [comment]
> Currently the image does change when the canvas changes.

Ahh, good point!  I do observe this behavior (e.g. shrinking the page and then re-expanding it will result in a loss of resolution on the image).

>  In that case I think it makes sense for the postfix to change but it also should be updated in the model

Agreed! That does make sense.  Since we are always updating the canvas and the postfix, then we could always push the updated filename (with the new postfix) back into the model so that everything remains consistent.  _However_, I dug into the history of this code and found that the `changed` check was added [when supporting default images](https://github.com/enketo/enketo-core/commit/82273a1777cd23606441199bdb256ba8c03cfeb3#diff-fe1ad45705c181d35fe5a5995f24818fd7144ea9f7333d1bdb1208f29921aaa1R348) to avoid the forms getting marked as "edited" when the image was loaded (since loading the image triggers an initial `canvasreload`).  With that in mind, it makes me wonder if we really want to mark the form as "edited" when resizing the canvas, etc.  Yes, technically the underlying image is changing, but really there has not been any true user input.... :thinking: 

Let me know what you think!  I can try and code up a different way of tracking if there has been any user input in the drawing and then let that determine if we generate a new postfix and push it to the model.  Or, we could go with my original suggestion with the understanding that the current canvas implementation has some known issues/limitations around `canvasreload` and that we do not need a new postfix for each canvas change....

**Comment by lognaturel** [comment]
> Yes, technically the underlying image is changing, but really there has not been any true user input.... 🤔

It depends on how the form server determines edit diffs. For example, ODK Central currently only uses the filename to determine that a file has changed and it is helpful to have an indication that there was resolution loss.

The true ideal would be to address the canvas resizing issue which can be quite problematic when using high-resolution imagery. Maybe you have some cycles to look into that? Again, we spent quite a bit of time on it that unfortunately ended in https://github.com/enketo/enketo/pull/1292 so I don't think it's going to be simple but with all of the information and test cases we put together, maybe with a fresh set of eyes you'd be able to get to a solution that doesn't break other things.

If not, we could try the simple original suggestion but I'd ask that you verify it for a broad range of cases (again, things like different page positions in pages mode, different order of resize and true edit, blank form vs edit, default no default, etc). It'd be a bit too bad to lose the filename change in case of resolution loss but better than having model and filename be out of sync.
