### ISSUE TITLE
Problem of multiselect widgets in a repeating group displaying the same selected options

### ISSUE THREAD

**Issue by gushil** [enketo/enketo#1337]
**Describe the bug**
The problem occurred when editing the form.

If the page contains multiple selectpickers with similar i18n keys (for example, in a repeating group), it will show the wrong selected text (even though the select options themselves are correct).

**To Reproduce**
Steps to reproduce the behavior. If applicable please include the smallest possible XLSForm or XForm (as zip or link).

1. Create a form with multilselect in a repeating group.
2. Add some (2 or more) multiselect in form enketo page. Select different options and keep some multiselect have same number of options selected (for example first multiselect has 3 options selected, second multiselect has 2 options selected.
3. Close the form page to save the input.
4. Edit the same form.
5. We will see that the second multiselect will display **3 selected** instead of **2 selected**.

**Expected behavior**
The third multiselect should display **2 selected**

**Screenshots**
This multiselect xform instances
```
<group_nm7ec42  enk:ordinal="1" >
	<multiselect2>a b c</multiselect2>
</group_nm7ec42>
<group_nm7ec42  enk:ordinal="2" >
	<multiselect2>a b</multiselect2>
</group_nm7ec42>
```
will give us
![wrong-select](https://github.com/user-attachments/assets/a84f56c6-a1a7-4c13-8cb4-db08d9464f35)
instead of (the right one)
![correct-select](https://github.com/user-attachments/assets/f149e47d-5fce-4afe-99e0-6fdb0a4e19ba)

**Browser and OS (please complete the following information):**

-   OS: Windows 11, MacOS
-   Browser: Chrome

**Additional context**
None.

**Comment by lognaturel** [comment]
XLSForm: [translation_key.xlsx](https://github.com/user-attachments/files/16630212/translation_key.xlsx)
