### ISSUE TITLE
Images on survey questions not being displayed 

### ISSUE THREAD

**Issue by FrankApiyo** [enketo/enketo#1352]
**Describe the bug**
In the choices sheet, a form with images labels as follows fails to render the images as expected:
```
media::image::wolof(wl)
```

**To Reproduce**
Upload the form linked below with the attached media files

[emojis_and_audios.zip](https://github.com/user-attachments/files/16963828/emojis_and_audios.zip)
[EVAL_FEP (1).xlsx](https://github.com/user-attachments/files/16963830/EVAL_FEP.1.xlsx)

**Screenshots**
![Screenshot from 2024-09-11 15-49-20](https://github.com/user-attachments/assets/58bbfc7c-1367-4c97-89d3-42180bbd26a0)

**What's expected**
![Screenshot from 2024-09-11 14-14-16](https://github.com/user-attachments/assets/0b82fa4f-0f57-415a-b407-e10bba8a1abf)

**Browser and OS (please complete the following information):**

-   OS: ubuntu
-   Browser: Chrome

**Comment by faith-mutua** [comment]
This has been resolved in stage.ona.io
