### ISSUE TITLE
Spanish translation is missing a URL for submission error

### ISSUE THREAD

**Issue by JacquelineMorrissette** [enketo/enketo#1370]
**Describe the bug**
Spanish translation of the submissionerror message is missing the URL to authenticate in a different tab

**To Reproduce**
Tested using KoboToolbox

1. Set form to single submission
2. Disallow submissions without authentication if not default
3. Open Enketo URL in a Spanish browser
4. Fill out form and submit data
5. Be prompted for authentication

**Expected behavior**
The prompt includes the link to authenticate in another tab

**Screenshots**
![image](https://github.com/user-attachments/assets/1520a978-21a8-4547-93a9-3917427bcb57)
![image](https://github.com/user-attachments/assets/c34a4559-6748-4668-ae9b-d4bd6e717cf9)

**Browser and OS (please complete the following information):**

-   OS: Windows 11 home
-   Browser Chrome/Firefox

**Additional context**
The workaround is to reload the browser in English and attempt to submit the form again

**Comment by alxndrsn** [comment]
This looks like a common problem - in many translations a value key is missing, has been translated into the target language, or has been corrupted.  The English key must be maintained for substitution to work.

Some examples:

> `en: The data server for your form or the Enketo server is down. Please try again later or contact __supportEmail__.`
> `vi: Dữ liệu gửi lên máy chủ trong form của bạn hoặc hiển thị Enketo đã bị ngừng. Hãy thử lại sau hoặc liên hệ _supportEmail_.`

> `uk: Вибрано __число__`
> `en: __number__ selected`

> `en: The data server for your form or the Enketo server is down. Please try again later or contact __supportEmail__.`
> `zh: 接收你的表格数据上传的数据服务器或是Enketo服务器宕机。请稍后再试或是联系 _技术支持邮箱_ 。`
