### ISSUE TITLE
SCSS compilation error when consuming enketo-core from Vite project

### ISSUE THREAD

**Issue by hansmbakker** [enketo/enketo#14]
**Describe the bug**
When consuming the enketo-core SCSS using [Vite](https://vitejs.dev/), I get an import issue from 
https://github.com/enketo/enketo/blob/15e164eabec6d49319eb720e28470ed854f6dfdc/packages/enketo-core/src/widget/date/datepicker-extended.scss#L1

> [vite:css] [sass] Can't find stylesheet to import.

The SCSS file assumes it is always in `/packages/enketo-core` (in the monorepo) but if you obtained the SCSS using `npm install enketo-core --save` then that path does not exist.
Also, the reference in the SCSS file misses the css extension (it ends with `.min`).

**To Reproduce**
1. Create a Vite project using `npm create vite@latest`
2. Add `enketo-core` and `sass` as dependencies to `package.json`
3. Run `npm install` and `npm run dev`
4. Add `<link rel="stylesheet" href="/node_modules/enketo-core/src/sass/plain/plain.scss" />` to your `index.html`

**Expected behavior**
No SCSS compilation error when consuming enketo-core

**Screenshots**
<img width="844" alt="image" src="https://github.com/enketo/enketo/assets/3463496/8de691c7-c29c-4b4f-8b22-1102b42eb9cd">

**Comment by lognaturel** [comment]
Thanks for filing this issue and sorry about that! If you'd like to put in a PR to fix, that would be appreciated, otherwise we'll try to get to it soon.

**Comment by MartijnR** [comment]
A fix might cause problems in the monorepo, but it would of course be great if it is possible for this to remain a relative URL instead of referring to monorepo file structure. Presumably this is not feasible.

Fwiw, a workaround that can be used with node-sass is to pass an importer function like this:

```js
 importer: (url) => {
                    const TARGET = '/packages/enketo-core';
                    const REPLACEMENT = './node_modules/enketo-core';
                    if (!url.startsWith(TARGET)) {
                        return null;
                    }

                    const repl = url.replace(TARGET, REPLACEMENT);
                    return {
                        file: path.resolve(__dirname, repl),
                    };
                },
```

**Comment by sergioestevess** [comment]
After thinking about it and actually trying to fix it, since that import path is correct, within the monorepo structure, if one wants to consume enketo-core with Vite, you could tell your Vite config to resolve that path to **your** _node_modules_ directory using alias.

```JavaScript
resolve: {
    alias: [
        {
            find: "/packages/enketo-core/node_modules",
            replacement: resolve(__dirname, "node_modules"),
        }
    ]
}
```

**Comment by lognaturel** [comment]
If that works for your needs, I agree we can close. Thanks!

**Comment by sergioestevess** [comment]
I support that, I don't think there's anything to fix here.

**Comment by lognaturel** [comment]
Thanks for digging deeper, @sergioestevess!
