### ISSUE TITLE
Redis SSL support for enketo-express

### ISSUE THREAD

**Issue by hansmbakker** [enketo/enketo#15]
**Is your feature request related to a problem? Please describe.**
In-transit encryption should be default nowadays as part of good security practices, especially when running on public cloud. When using Azure Redis Cache, I would like to connect to it using SSL.

Enketo Express does not seem to allow connecting to Redis via SSL - it only allows to set hostname, port and password.

https://github.com/enketo/enketo-express/blob/804e13b59b36273b926d3a3acadd4486c6fb3a0b/app/lib/db.js#L4-L10

**Describe the solution you'd like**
Support for a connection string using the `rediss` protocol, or allow specifying that SSL should be used given the port.

**More background**
According to https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-nodejs-get-started#connect-to-the-cache it is possible to [supply node-redis with a connection string based on the `rediss` protocol](https://github.com/redis/node-redis/blob/a8b81bdd01329252466eb1dd608b2a92b960c3ae/docs/client-configuration.md#createclient-configuration), but that is based on the latest node-redis version.
According to https://github.com/enketo/enketo/issues/9, the upgrade from node-redis v3 to v4 still needs to be done

**Comment by lognaturel** [comment]
Thanks so much for moving this to the monorepo!

Related: https://github.com/enketo/enketo-express/pull/538 and https://github.com/enketo/enketo-express/pull/546

**Comment by lognaturel** [comment]
> In-transit encryption should be default nowadays as part of good security practices, especially when running on public cloud

Is your application server also on Azure? Is your redis db exposed to the Internet? Ideally it would not be. In that case, it's relatively common to use HTTP within a secure network. In fact, services that aren't externally exposed would either have to use a wildcard or self-signed cert which has its own problems.

As I wrote at https://github.com/enketo/enketo/issues/17#issuecomment-1819959904, I'd also encourage you to first consider whether you actually do need to run redis separately.

**Comment by hansmbakker** [comment]
Our application server is indeed also on Azure, and we use Private Endpoints (via Private Link) to communicate privately between the application server and Redis.

I agree it is sometimes easier to fallback to HTTP but even in closed networks, it becomes more and more common to use encrypted connections (and it is seen as a best practice).
With Azure Redis, the platform will provide the certificate, and within a container context, technologies to encrypt the communication between containers are upcoming (usually via sidecars, like istio or dapr, and there the certificate management is done by those sidecars).

I'll respond to #17 separately
