### ISSUE TITLE
Markdown special characters are transformed even inside hyperlink URLs

### ISSUE THREAD

**Issue by jnm** [enketo/enketo#767]
**Describe the bug**
The Markdown processor appears to convert `_text_` to `<em>text</em>` before considering hyperlinks, such that the following form:

type | name | label
-- | -- | --
`note` | `underscore_link` | `[i like underscores](https://fun.stuff/great_job_excellent)`

…renders the note as:
```html
<a href="https://fun.stuff/great%3Cem%3Ejob%3C/em%3Eexcellent" rel="noopener" target="_blank">i like underscores</a>
```

**To Reproduce**
Minimal form is above; for convenience, here is the same in XLSX: [underscore-links.xlsx](https://github.com/enketo/enketo-express/files/8137079/underscore-links.xlsx)
1. Create a form where a label contains a hyperlink whose URL contains a pair of underscores;
2. View the form in Enketo 3.1.0 (tested with https://getodk.org/xlsform/ and https://enketo.getodk.org/);
3. Note that the URL has become mangled with `<em>` and `</em>` replacing the underscores.

This also happens if two links are inserted and each link contains a single underscore: https://github.com/kobotoolbox/kpi/issues/3698.

**Expected behavior**
Pairs of underscores within hyperlink URLs should not be converted to `<em>` and `</em>`.

**Browser and OS (please complete the following information):**
 - OS: Linux (desktop)
 - Browser: Firefox 97.0, Chrome 98.0.4758.102

**Additional context**
The form XML contains `<label>[i like underscores](https://fun.stuff/great_job_excellent)</label>`, which is correct and should eliminate other software (pyxform, etc.) as the cause.

**Comment by lognaturel** [comment]
Closed by https://github.com/enketo/enketo/commit/5f9e31f16e434dcc469fbdfd195dc0516689a8cb
