### ISSUE TITLE
Feat: Add configurable events to interact with frontend app

### ISSUE THREAD

**Issue by amit-s19** [enketo/enketo#938]
## Is your feature request related to a problem? Please describe.
When integrating Enketo Forms with frontend applications made on React, Angular, plain html css etc it becomes for these apps to interact with the form directly.

## Describe the solution you'd like
Events should be provided by default like `onFormChange, onSubmit, onSubmitSuccessful, onFailure, onFileUpload,` etc which would allow the frontend application to interact with the enketo form.

## Describe alternatives you've considered
We've added events manually in `controller-webform.js` to suit our needs. For example, an event listener was added to `events.XFormsValueChanged` to listen to form changes event and then data was `broadcasted` to the frontend application.

```
  document.addEventListener(events.XFormsValueChanged().type, async (e) => {
        /*
        * Perform actions on event change
        * /
        
       // Broadcast back to frontend
        await formController.broadcastFormDataUpdate(form.getDataStr(), {});
}
```

Note : This feat/issue is linked to previous issues(s) enketo/enketo#940, enketo/enketo#939

**Comment by lognaturel** [comment]
Discussion can continue at https://github.com/enketo/enketo/issues/1314
